<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SeedDormitoryCorridor.Assets\SeedDormitoryCorridor.Assets.csproj" />
    <ProjectReference Include="..\SeedDormitoryCorridor.Configuration\SeedDormitoryCorridor.Configuration.csproj" />
    <ProjectReference Include="..\SeedDormitoryCorridor.Platform.Windows\SeedDormitoryCorridor.Platform.Windows.csproj" />
    <ProjectReference Include="..\SeedDormitoryCorridor.Rendering\SeedDormitoryCorridor.Rendering.csproj" />
    <ProjectReference Include="..\SeedDormitoryCorridor.Runtime\SeedDormitoryCorridor.Runtime.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>..\..\assets\app.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="..\..\assets\builtin-sweeper-ex\**\*">
      <Link>assets\builtin-sweeper-ex\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Include="..\..\assets\builtin-tian-ruo\**\*">
      <Link>assets\builtin-tian-ruo\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Include="..\..\assets\builtin-su-xiao\**\*">
      <Link>assets\builtin-su-xiao\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Include="..\..\assets\builtin-seed\**\*">
      <Link>assets\builtin-seed\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

</Project>
